### PR TITLE
News: ARM USB armory platform support.

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by xtraeme** [comment]
It's perfect, I'm generating the images right now.

Will apply it as soon as the images are ready, thanks!

**Comment by xtraeme** [comment]
Hmm would be nice to add a link to the official site to see hw specs, etc.

**Comment by Gottox** [comment]
See: https://github.com/voidlinux/voidlinux.github.com/pull/12/files#diff-294378058664a7d1ef2eb8805f4eaa90R32

**Comment by xtraeme** [comment]
True, sorry didn't see it.

**Pull request merged**
